extra:
  python:
    source: provider/file_tools.py
identity:
  author: nexusai
  description:
    en_US: A collection of various tools for handling file object.
    ja_JP: ファイルオブジェクトを扱うためのさまざまなツールのコレクション。
    pt_BR: Uma coleção de várias ferramentas para manipular objetos de arquivo.
    zh_Hans: 用于处理文件对象的各种工具集合。
  icon: icon.svg
  label:
    en_US: File Tools
  name: file_tools
tools:
- tools/dump_to_json/dump_to_json.yaml
- tools/embed_as_base64/embed_as_base64.yaml
- tools/get_download_url/get_download_url.yaml
- tools/save_as_file/save_as_file.yaml
