credentials_for_provider:
  key:
    help:
      en_US: Enter your Supabase API key.
      ja_JP: Supabase API キーを入力してください。
      zh_CN: 输入你的 Supabase API 密钥。
    label:
      en_US: Supabase Key
      ja_JP: Supabase キー
      zh_CN: Supabase 密钥
    placeholder:
      en_US: Enter your Supabase key
      ja_JP: Supabase キーを入力してください
      zh_CN: 输入你的 Supabase 密钥
    required: true
    type: secret-input
    url: https://supabase.com/dashboard/project/<project_id>/settings/api-keys
  url:
    help:
      en_US: Enter your Supabase project URL.
      ja_JP: Supabase プロジェクトの URL を入力してください。
      zh_CN: 输入你的 Supabase 项目地址。
    label:
      en_US: Supabase URL
      ja_JP: Supabase URL
      zh_CN: Supabase 地址
    placeholder:
      en_US: https://your-project.supabase.co
      ja_JP: https://your-project.supabase.co
      zh_CN: https://your-project.supabase.co
    required: true
    type: text-input
    url: https://supabase.com/dashboard/project/<project_id>/settings/api
extra:
  python:
    source: provider/supabase.py
identity:
  author: nexusai
  description:
    en_US: Supabase is an open-source backend-as-a-service that provides a real-time
      database, authentication, and storage built on top of PostgreSQL.
    ja_JP: Supabase は、PostgreSQL を基盤としたリアルタイムデータベース、認証、ストレージを提供するオープンソースのバックエンドサービスです。
    zh_CN: Supabase 是一个开源的后端即服务（BaaS），提供基于 PostgreSQL 的实时数据库、身份验证和存储功能。
  icon: icon.svg
  label:
    en_US: Supabase
    ja_JP: Supabase
    zh_CN: Supabase
  name: supabase
tools:
- tools/create_a_row.yaml
- tools/delete_row.yaml
- tools/get_rows.yaml
- tools/update_row.yaml
