extra:
  python:
    source: provider/ppt.py
identity:
  author: nexusai
  description:
    en_US: Convert Markdown content to PowerPoint presentations
    pt_BR: Converter conteúdo Markdown para apresentações PowerPoint
    zh_Hans: 将Markdown内容转换为PowerPoint演示文稿
  icon: icon.svg
  label:
    en_US: PPT
    pt_BR: PPT
    zh_Hans: PPT
  name: ppt
tools:
- tools/ppt.yaml
