extra:
  python:
    source: provider/remove_markdown.py
identity:
  author: nexusai
  description:
    en_US: Remove Markdown formatting from LLM output
  icon: icon.svg
  label:
    en_US: Remove Markdown
  name: remove_markdown
tools:
- tools/remove_markdown.yaml
