description:
  human:
    en_US: Del row
    zh_Hans: 删除行
  llm: A tool for Del row. (删除行)
extra:
  python:
    source: tools/del_row.py
identity:
  author: Wit Meng
  label:
    en_US: Del row
    zh_Hans: 删除行
  name: del_row
parameters:
- form: llm
  human_description:
    en_US: the unionId of Operator
    zh_Hans: 操作人的unionId
  label:
    en_US: the unionId
    zh_Hans: 操作人的unionId
  llm_description: 操作人的unionId
  name: operator_id
  required: true
  type: string
- form: llm
  human_description:
    en_US: The ID of the table, supports table URL input, e.g., https://alidocs.dingtalk.com/i/nodes/XXXXSlNkL2dUTCJcPRgentXXX
    zh_Hans: 表格的ID，支持表格 URL 输入，如：https://alidocs.dingtalk.com/i/nodes/XXXXSlNkL2dUTCJcPRgentXXX
  label:
    en_US: Table ID
    zh_Hans: 表格的链接
  llm_description: 表格的ID，支持表格 URL 输入，如：https://alidocs.dingtalk.com/i/nodes/XXXXSlNkL2dUTCJcPRgentXXX
  name: table_id
  required: true
  type: string
- form: llm
  human_description:
    en_US: Sheet ID, either sheet_id or sheet_name must be filled.
    zh_Hans: 工作表 ID，与 sheet_name 二者其一必填。
  label:
    en_US: sheet_id
    zh_Hans: 工作表 ID
  llm_description: 工作表 ID，与 sheet_name 二者其一必填。
  name: sheet_id
  required: false
  type: string
- form: llm
  human_description:
    en_US: Sheet name, either sheet_id or sheet_name must be filled.
    zh_Hans: 工作表名称，与 sheet_id 二者其一必填。
  label:
    en_US: sheet_name
    zh_Hans: 工作表名称
  llm_description: 工作表名称，与 sheet_id 二者其一必填。
  name: sheet_name
  required: false
  type: string
- form: llm
  human_description:
    en_US: the row index, e.g., 1, 2, 3
    zh_Hans: 指定起始行号，例如： 1, 2, 3
  label:
    en_US: the row index
    zh_Hans: 行号
  llm_description: 指定行起始行号，例如： 1, 2, 3
  name: start_row
  required: true
  type: string
- form: llm
  human_description:
    en_US: the Count of rows for delete, 0 means not delete
    zh_Hans: 删除行数, 0表示不删除
  label:
    en_US: Counts of rows for delete
    zh_Hans: 删除行数
  llm_description: 删除行数
  name: row_count
  required: true
  type: string  