identity:
  name: list-file
  author: witmeng
  label:
    en_US: list file
    zh_Hans: 文件列表
description:
  human:
    en_US: list file
    zh_Hans: 文件列表
  llm: list file
parameters:
  - form: llm
    human_description:
      en_US: datasets id
      zh_Hans: 數據集ID
    label:
      en_US: datasets id
      zh_Hans: 數據集ID
    llm_description:  數據集ID
    name: datasets_id
    required: true
    type: string 
  - form: llm
    human_description:
      en_US: page number, default 1
      zh_Hans: 頁碼，默認1
    label:
      en_US: page
      zh_Hans: 頁碼
    llm_description: 頁碼
    name: page
    required: false
    type: number
  - form: llm
    human_description:
      en_US: page size, default 30
      zh_Hans: 每頁數據量，默認30
    label:
      en_US: pageSize
      zh_Hans: 頁數量
    llm_description: 每頁數據量，默認30
    name: pageSize
    required: false
    type: number      
extra:
  python:
    source: tools/list-file.py
