credentials_for_provider:
  integration_token:
    help:
      en_US: Get your integration token from the Notion Integrations page
      ja_JP: Notion統合ページから統合トークンを取得してください
      pt_BR: Obtenha seu token de integração na página de Integrações do Notion
      zh_Hans: 从 Notion 集成页面获取您的接口令牌
      zh_Hant: 從 Notion 整合頁面獲取您的整合權杖
    label:
      en_US: Integration Secret
      ja_JP: 統合シークレット (Integration Secret)
      pt_BR: Segredo de Integração (Integration Secret)
      zh_Hans: 接口密钥 (Integration Secret)
      zh_Hant: 整合密鑰 (Integration Secret)
    placeholder:
      en_US: Enter your Notion Integration Token
      ja_JP: Notion統合トークンを入力してください
      pt_BR: Digite seu Token de Integração do Notion
      zh_Hans: 输入您的 Notion 接口令牌
      zh_Hant: 輸入您的 Notion 整合權杖
    required: true
    type: secret-input
    url: https://www.notion.so/profile/integrations
extra:
  python:
    source: provider/notion.py
identity:
  author: nexusai
  description:
    en_US: Connect to Notion to search, query databases, and create content
    ja_JP: Notionに接続して検索、データベースのクエリ、コンテンツの作成を行います
    pt_BR: Conecte-se ao Notion para pesquisar, consultar bancos de dados e criar
      conteúdo
    zh_Hans: 连接 Notion 以搜索、查询数据库和创建内容
    zh_Hant: 連接 Notion 以搜索、查詢數據庫和創建內容
  icon: icon.svg
  label:
    en_US: Notion
    ja_JP: Notion
    pt_BR: Notion
    zh_Hans: Notion
    zh_Hant: Notion
  name: notion
tools:
- tools/search_notion.yaml
- tools/query_database.yaml
- tools/create_page.yaml
- tools/retrieve_page.yaml
- tools/update_page.yaml
- tools/retrieve_database.yaml
- tools/create_database.yaml
- tools/update_database.yaml
- tools/retrieve_comments.yaml
- tools/create_comment.yaml
