credentials_for_provider:
  scrapegraphai_api_key:
    help:
      en_US: How to get your ScrapeGraphAI API Key
      pt_BR: Como obter sua chave API ScrapeGraphAI
      zh_Hans: 如何获取您的 ScrapeGraphAI API 密钥
    label:
      en_US: ScrapeGraphAI API Key
      pt_BR: Chave API ScrapeGraphAI
      zh_Hans: ScrapeGraphAI API 密钥
    placeholder:
      en_US: Enter your ScrapeGraphAI API Key
      pt_BR: Digite sua chave API ScrapeGraphAI
      zh_Hans: 请输入您的 ScrapeGraphAI API 密钥
    required: true
    type: secret-input
    url: https://dashboard.scrapegraphai.com/
extra:
  python:
    source: provider/scrapegraphai.py
identity:
  author: nexusai
  description:
    en_US: ScrapeGraphAI integration for LLM powered scraping
    pt_BR: Integração ScrapeGraphAI para web scraping com LLM
    zh_Hans: ScrapeGraphAI 集成，用于 LLM 驱动的网页抓取
  icon: icon.svg
  label:
    en_US: ScrapeGraphAI
    pt_BR: ScrapeGraphAI
    zh_Hans: ScrapeGraphAI
  name: scrapegraphai
tools:
- tools/scrapegraphai.yaml
