credentials_for_provider:
  telegraph_access_token:
    en_US: Get your Access Token from Telegraph
    help: null
    ja_JP: Telegraphからアクセストークンを取得
    label:
      en_US: Telegraph Access Token
      ja_JP: Telegraph Access Token
      pt_BR: Telegraph Access Token
      zh_Hans: Telegraph Access Token
    placeholder:
      en_US: Please input your Telegraph Access Token
      ja_JP: Telegraphアクセストークンを入力してください
      pt_BR: Por favor, insira seu Token de Acesso do Telegraph
      zh_Hans: 请输入您的Telegraph访问令牌
    pt_BR: Obtenha seu Token de Acesso do Telegraph
    required: true
    type: secret-input
    url: https://telegra.ph/api#createAccount
    zh_Hans: 从Telegraph获取访问令牌
extra:
  python:
    source: provider/telegraph.py
identity:
  author: nexusai
  description:
    en_US: A Telegraph plugin that allows you to publish your content easily
    ja_JP: コンテンツを簡単に公開できるTelegraphプラグイン
    pt_BR: Um plugin do Telegraph que permite publicar seu conteúdo facilmente
    zh_Hans: 一个让您轻松发布内容的Telegraph插件
  icon: icon.jpg
  label:
    en_US: Telegraph
    pt_BR: Telegraph
    zh_Hans: Telegraph
  name: telegraph
  tags:
  - social
  - productivity
  - utilities
tools:
- tools/telegraph.yaml
- tools/telegraph_advanced.yaml
