identity:
  name: no_markdown
  author: himicoswilson
  label:
    en_US: No Markdown
    zh_Hans: 移除Markdown
    pt_BR: Remover Markdown
description:
  human:
    en_US: Remove the markdown syntax
    zh_Hans: 移除Markdown语法
    pt_BR: Remover a sintaxe markdown
  llm: Remove the markdown syntax
parameters:
  - name: text
    type: string
    required: true
    label:
      en_US: Text
      zh_Hans: 文本
      pt_BR: Texto
    human_description:
      en_US: Remove the text markdown syntax
      zh_Hans: 移除文本中的Markdown语法
      pt_BR: Remover a sintaxe markdown do texto
    llm_description: Remove the text markdown syntax
    form: llm
  - name: preserve_links
    type: boolean
    required: true
    default: true
    label:
      en_US: Preserve Links
      zh_Hans: 保留链接
      pt_BR: Preservar Links
    human_description:
      en_US: Whether to preserve URLs in the output
      zh_Hans: 是否在输出中保留URL链接
      pt_BR: Se deve preservar URLs na saída
    llm_description: Whether to preserve URLs in the output
    form: form
extra:
  python:
    source: tools/no_markdown.py
