extra:
  python:
    source: provider/markdown2html.py
identity:
  author: nexusai
  description:
    en_US: Convert content from Markdown to HTML
    pt_BR: Converter conteúdo de Markdown para HTML
    zh_Hans: 将内容从 Markdown 转换为 HTML
  icon: icon.svg
  label:
    en_US: markdown2html
    pt_BR: markdown2html
    zh_Hans: markdown2html
  name: markdown2html
tools:
- tools/markdown2html.yaml
