credentials_for_provider:
  playwright_uri:
    help:
      en_US: For example `ws://host.docker.internal:3003`
      zh_Hans: 例如 `ws://host.docker.internal:3003`
    label:
      en_US: Playwright URI
    placeholder:
      en_US: Please enter the Playwright URI
      zh_Hans: 请输入Playwright URI
    required: true
    type: secret-input
extra:
  python:
    source: provider/playwright.py
identity:
  author: nexusai
  description:
    en_US: A tool can be used to automate the browser with playwright script.
    zh_Hans: 一个可以使用 playwright 脚本自动化浏览器的工具
  icon: icon.svg
  label:
    en_US: playwright
    pt_BR: playwright
    zh_Hans: playwright
  name: playwright
tools:
- tools/playwright.yaml
