credentials_for_provider:
  attio_api_token:
    help:
      en_US: Get your API token from Attio Workspace Settings > Developers > New Access
        Token
      ja_JP: Attio ワークスペース設定 > 開発者 > 新しいアクセストークン から API トークンを取得してください
      pt_BR: Obtenha seu token da API em Attio Configurações do Espaço de Trabalho
        > Desenvolvedores > Novo Token de Acesso
      zh_Hans: 从 Attio 工作区设置 > 开发者 > 新建访问令牌 获取您的 API 令牌
    label:
      en_US: Attio API Token
      ja_JP: Attio API トークン
      pt_BR: Token da API Attio
      zh_Hans: Attio API 令牌
    placeholder:
      en_US: Enter your Attio API token
      ja_JP: Attio API トークンを入力してください
      pt_BR: Digite seu token da API Attio
      zh_Hans: 输入您的 Attio API 令牌
    required: true
    type: secret-input
    url: https://attio.com/help/apps/other-apps/generating-an-api-key
extra:
  python:
    source: provider/attio.py
identity:
  author: nexusai
  description:
    en_US: Connect to Attio to manage database records and perform CRUD operations
    ja_JP: Attio に接続してデータベースレコードを管理し、CRUD操作を実行します
    pt_BR: Conecte-se ao Attio para gerenciar registros de banco de dados e executar
      operações CRUD
    zh_Hans: 连接到 Attio 以管理数据库记录并执行 CRUD 操作
  icon: icon.svg
  label:
    en_US: Attio
    ja_JP: Attio
    pt_BR: Attio
    zh_Hans: Attio
  name: attio
  tags:
  - business
  - productivity
tools:
- tools/list_objects.yaml
- tools/list_lists.yaml
- tools/list_records.yaml
- tools/list_entries.yaml
- tools/list_attributes.yaml
- tools/add_records.yaml
- tools/delete_records.yaml
- tools/add_entries.yaml
- tools/delete_entries.yaml
- tools/create_objects.yaml
