credentials_for_provider:
  tavily_api_key:
    help:
      en_US: Get your Tavily API key from tavily
    label:
      en_US: Tavily API Key
    placeholder:
      en_US: Enter your Tavily API key here
    required: true
    type: secret-input
    url: https://tavily.com/
extra:
  python:
    source: provider/deep_research.py
identity:
  author: nexusai
  description:
    en_US: Deep Research, is a powerful tool designed to enhance Dify&#39;s capabilities
      by providing a robust web search interface. It leverages the Tavily API to conduct
      comprehensive web searches and optionally retrieve the full content of relevant
      web pages. This real-time data access, combined with Dify&#39;s internal LLM
      orchestration, enables dynamic, multi-step research workflows that can delve
      deep into any topic, synthesize information, and spark curiosity.
    pt_BR: Deep Research, is a powerful tool designed to enhance Dify&#39;s capabilities
      by providing a robust web search interface. It leverages the Tavily API to conduct
      comprehensive web searches and optionally retrieve the full content of relevant
      web pages. This real-time data access, combined with Dify&#39;s internal LLM
      orchestration, enables dynamic, multi-step research workflows that can delve
      deep into any topic, synthesize information, and spark curiosity.
    zh_Hans: Deep Research, is a powerful tool designed to enhance Dify&#39;s capabilities
      by providing a robust web search interface. It leverages the Tavily API to conduct
      comprehensive web searches and optionally retrieve the full content of relevant
      web pages. This real-time data access, combined with Dify&#39;s internal LLM
      orchestration, enables dynamic, multi-step research workflows that can delve
      deep into any topic, synthesize information, and spark curiosity.
  icon: icon.svg
  label:
    en_US: deep_research
    pt_BR: deep_research
    zh_Hans: deep_research
  name: deep_research
  tags:
  - search
tools:
- tools/deep_research.yaml
