identity:
  name: get_task_status
  author: lysonober
  label:
    en_US: "Get Task Status"
    zh_Hans: "获取任务状态"
    ja_JP: "タスクステータスを取得"
    pt_BR: "Obter Status da Tarefa"
description:
  human:
    en_US: "Check the current status of a browser automation task. Returns a simple status value (created, running, finished, stopped, paused, or failed)."
    zh_Hans: "检查浏览器自动化任务的当前状态。返回一个简单的状态值（已创建、运行中、已完成、已停止、已暂停或失败）。"
    ja_JP: "ブラウザ自動化タスクの現在のステータスを確認します。シンプルなステータス値（作成済み、実行中、完了、停止、一時停止、または失敗）を返します。"
    pt_BR: "Verifique o status atual de uma tarefa de automação do navegador. Retorna um valor de status simples (criado, em execução, concluído, parado, pausado ou falhou)."
  llm: "This tool checks the current status of a browser automation task by its ID. It makes a GET request to the /api/v1/task/{task_id}/status endpoint and returns a simple status string. The possible status values are: 'created' (initialized but not started), 'running' (currently executing), 'finished' (completed successfully), 'stopped' (manually stopped), 'paused' (temporarily paused), or 'failed' (encountered an error). This is more lightweight than getting the full task details when you only need to know the current execution state."
parameters:
  - name: task_id
    type: string
    required: true
    label:
      en_US: "Task ID"
      zh_Hans: "任务 ID"
      ja_JP: "タスク ID"
      pt_BR: "ID da Tarefa"
    human_description:
      en_US: "The unique identifier of the task you want to check the status for. This is the ID returned when you created the task."
      zh_Hans: "您想要检查状态的任务的唯一标识符。这是您创建任务时返回的 ID。"
      ja_JP: "ステータスを確認したいタスクの一意の識別子。これはタスク作成時に返された ID です。"
      pt_BR: "O identificador único da tarefa para a qual você deseja verificar o status. Este é o ID retornado quando você criou a tarefa."
    llm_description: "The unique identifier (ID) of the task you want to check the status for. This is the ID string that was returned when you created the task using the run_task tool."
    form: llm
extra:
  python:
    source: tools/get_task_status.py
