extra:
  python:
    source: provider/lark_notify.py
identity:
  author: nexusai
  description:
    en_US: Send notifications to Lark group chats, supporting both text and card messages.
    ja_JP: Larkグループチャットに通知を送信し、テキストメッセージとカードメッセージの両方をサポートします。
    pt_BR: Envie notificações para chats em grupo do Lark, suportando mensagens de
      texto e cartão.
    zh_Hans: 向飞书群聊发送通知，支持文本消息和卡片消息。
  icon: icon.svg
  label:
    en_US: Lark Notification
    ja_JP: Lark 通知
    pt_BR: Notificação do Lark
    zh_Hans: 飞书通知
  name: lark_notify
tools:
- tools/lark_card.yaml
- tools/lark_text.yaml
