CREATE TABLE scheduled_tasks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'PRIMARY KEY',
    name VARCHAR(255) NOT NULL COMMENT 'TASK NAME',
    description VARCHAR(255) COMMENT 'TASK DESCRIPTION',
    task_type ENUM('one_time', 'recurring') NOT NULL COMMENT 'TASK TYPE: ONE_TIME OR RECURRING',
    status TINYINT DEFAULT 1 COMMENT 'TASK STATUS: 1-ENABLED, 2-DISABLED, 3-PAUSED, 4-DELETED',
    
    -- USER AND APPLICATION ASSOCIATION FIELDS
    user_id BIGINT NOT NULL COMMENT 'USER ID',
    app_id BIGINT NOT NULL COMMENT 'APPLICATION ID',
    workflow_id BIGINT NOT NULL COMMENT 'WORKFLOW ID',
    input JSON NOT NULL COMMENT 'INPUT DATA FOR TASK EXECUTION',
    
    -- EXECUTION TIME FIELDS
    start_time DATETIME NOT NULL COMMENT 'TASK START TIME',
    end_time DATETIME NULL COMMENT 'TASK END TIME (NULL FOR UNLIMITED)',
    next_run_time DATETIME NOT NULL COMMENT 'NEXT EXECUTION TIME',
    
    -- REPETITION PATTERN FIELDS
    repeat_type ENUM('none', 'minute', 'hour', 'day', 'week', 'month', 'year') DEFAULT 'none' COMMENT 'REPETITION TYPE',
    repeat_interval INT DEFAULT 1 COMMENT 'REPETITION INTERVAL',
    repeat_days VARCHAR(255) NULL COMMENT 'REPEAT DAYS FOR WEEKLY TASKS (E.G., [1,3,5] FOR MONDAY, WEDNESDAY, FRIDAY)',
    repeat_day_of_month INT NULL COMMENT 'DAY OF MONTH FOR MONTHLY TASKS',
    repeat_month INT NULL COMMENT 'MONTH FOR YEARLY TASKS',
    repeat_day_of_year INT NULL COMMENT 'DAY OF YEAR FOR YEARLY TASKS',
    
    -- TASK EXECUTION FIELDS
    task_data JSON NOT NULL COMMENT 'TASK EXECUTION DATA',
    last_run_time DATETIME NULL COMMENT 'LAST EXECUTION TIME',
    last_run_status TINYINT NULL COMMENT 'LAST EXECUTION STATUS: 1-SUCCESS, 2-FAILED, 3-RUNNING',
    execution_count INT DEFAULT 0 COMMENT 'TOTAL EXECUTION COUNT',
    max_executions INT DEFAULT 0 COMMENT 'MAXIMUM EXECUTION COUNT (0 FOR UNLIMITED)',
    
    -- TIMESTAMP FIELDS
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATION TIMESTAMP',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'LAST UPDATE TIMESTAMP',
    
    INDEX idx_next_run_time (next_run_time) COMMENT 'INDEX FOR NEXT RUN TIME QUERIES',
    INDEX idx_status (status) COMMENT 'INDEX FOR STATUS QUERIES',
    INDEX idx_task_type (task_type) COMMENT 'INDEX FOR TASK TYPE QUERIES',
    INDEX idx_user_id (user_id) COMMENT 'INDEX FOR USER ID QUERIES',
    INDEX idx_app_id (app_id) COMMENT 'INDEX FOR APPLICATION ID QUERIES',
    INDEX idx_workflow_id (workflow_id) COMMENT 'INDEX FOR WORKFLOW ID QUERIES'
) COMMENT 'SCHEDULED TASKS TABLE FOR MANAGING RECURRING AND ONE-TIME TASK EXECUTIONS';

-- ADD SCHEDULED TASK ID TO APP_RUNS TABLE
ALTER TABLE app_runs ADD COLUMN scheduled_task_id BIGINT DEFAULT 0 COMMENT 'SCHEDULED TASK ID' AFTER type;

-- ADD INDEX FOR SCHEDULED TASK ID
ALTER TABLE app_runs ADD INDEX idx_scheduled_task_id (scheduled_task_id) COMMENT 'INDEX FOR SCHEDULED TASK ID QUERIES';