INSERT INTO `suppliers` (`id`, `name`, `mode`, `created_time`, `updated_time`, `status`)
VALUES (NULL, 'Doubao', '1', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `suppliers` (`id`, `name`, `mode`, `created_time`, `updated_time`, `status`)
VALUES (NULL, 'Anthropic', '1', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `supplier_configurations` (`id`, `team_id`, `supplier_id`, `config`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '4', '{"api_key": "", "base_url": "https://ark.cn-beijing.volces.com/api/v3"}', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `supplier_configurations` (`id`, `team_id`, `supplier_id`, `config`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '5', '{"api_key": "", "base_url": "https://api.anthropic.com"}', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '4', 'Doubao-1.5-pro-256k', '1', '1', '256000', '12000', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '4', 'Doubao-1.5-pro-32k', '1', '1', '32000', '12000', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '4', 'Doubao-1.5-lite-32k', '1', '1', '32000', '12000', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '4', 'Doubao-pro-256k', '1', '1', '256000', '4000', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '4', 'Doubao-lite-128k', '1', '1', '128000', '4000', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`)
VALUES
(NULL, '5', 'Anthropic-1.5-pro-256k', '1', '1', '256000', '12000', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '5', 'Anthropic-1.5-pro-32k', '1', '1', '32000', '12000', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '5', 'Anthropic-1.5-lite-32k', '1', '1', '32000', '12000', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '5', 'Anthropic-pro-256k', '1', '1', '256000', '4000', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '5', 'Anthropic-lite-128k', '1', '1', '128000', '4000', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '15', '{"model": "ep-20250213164639-kgtq2", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 1}', '0', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '16', '{"model": "ep-20250213145156-lgdnr", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 2}', '0', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '17', '{"model": "ep-20250213164550-m586m", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 3}', '0', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '18', '{"model": "ep-20250213164639-kgtq2", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 4}', '0', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`)
VALUES (NULL, '1', '19', '{"model": "ep-20250213164724-95xlf", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 5}', '0', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`)
VALUES
(NULL, '1', '10', '{"model": "ep-20250213164639-anth_pro256", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 1}', '0', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '1', '11', '{"model": "ep-20250213145156-anth_pro32", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 2}', '0', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '1', '12', '{"model": "ep-20250213164550-anth_lite32", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 3}', '0', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '1', '13', '{"model": "ep-20250213164639-anth_pro256_v2", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 4}', '0', CURRENT_TIMESTAMP, NULL, '1'),
(NULL, '1', '14', '{"model": "ep-20250213164724-anth_lite128", "temperature": 0.7, "model_kwargs": {}, "base_url": null, "organization": null, "openai_proxy": null, "timeout": null, "max_retries": 2, "streaming": false, "n": 1, "max_tokens": null, "tiktoken_model_name": null, "default_headers": null, "default_query": null, "http_client": null, "http_async_client": null, "stop_sequences": null, "sort_order": 5}', '0', CURRENT_TIMESTAMP, NULL, '1');

ALTER TABLE `model_configurations`
	ADD COLUMN `sort_order` TINYINT(11) NOT NULL COMMENT 'Model Sort Order' AFTER `default_used`;

INSERT INTO `apps` (`id`, `team_id`, `user_id`, `name`, `description`, `icon`, `icon_background`, `mode`, `enable_api`, `api_token`, `is_public`, `publish_status`, `attrs_are_visible`, `execution_times`, `created_time`, `updated_time`, `status`) VALUES (2652, 1, 32, 'File Generation Tool', 'Generate a uniquely named file based on the given content and file suffix, and store it in the specified directory.', NULL, NULL, 4, 0, NULL, 1, 1, 1, 37, '2025-02-08 14:40:48', '2025-02-17 17:14:54', 1);
INSERT INTO `custom_tools` (`id`, `team_id`, `user_id`, `app_id`, `config`, `input_variables`, `dependencies`, `code`, `output_type`, `output_variables`, `publish_status`, `published_time`, `created_time`, `updated_time`, `status`) VALUES (325, 1, 32, 2652, NULL, '{"name": "inputs", "type": "object", "properties": {"content": {"name": "content", "type": "string", "value": null, "required": true, "max_length": 0, "display_name": "File Content"}, "file_suffix": {"name": "file_suffix", "type": "string", "value": null, "required": true, "max_length": 0, "display_name": "File Suffix"}}, "display_name": "Inputs"}', '{"python3": []}', '{"python3":"import os\\nimport uuid\\n\\ndef main(content: str, file_suffix: str) -> dict:\\n    try:\\n        # Generate a random UUID for the file name\\n        unique_id = uuid.uuid4()\\n\\n        # Split the file_suffix by \'.\' and take the last part as the actual suffix\\n        suffix_parts = file_suffix.split(\'.\')\\n        if len(suffix_parts) > 1:\\n            actual_suffix = suffix_parts[-1]\\n        else:\\n            actual_suffix = file_suffix\\n\\n        # Ensure the suffix starts with a dot\\n        if not actual_suffix.startswith(\'.\'):\\n            actual_suffix = f\\".{actual_suffix}\\"\\n\\n        # Construct the file name with the correct suffix\\n        file_name = f\\"{unique_id}{actual_suffix}\\"\\n\\n        # Create the storage directory if it doesn\'t exist\\n        storage_dir = \'/storage\'\\n        os.makedirs(storage_dir, exist_ok=True)\\n\\n        # Create the full storage path\\n        storage_path = os.path.join(storage_dir, file_name)\\n\\n        # Write the content to the file\\n        with open(storage_path, \'w\') as file:\\n            file.write(content)\\n        status = \'True\'\\n    except Exception as e:\\n        # Capture any exception and set the status to the exception message\\n        status = str(e)\\n\\n    # Return the status and the file path\\n    return {\'status\': status, \'file_path\': f\\"file://{storage_path}\\"}"}', 4, '{"name": "outputs", "type": "object", "properties": {"status": {"name": "status", "type": "string", "value": null, "max_length": 0, "display_name": "Execution Status"}, "file_path": {"name": "file_path", "type": "string", "value": null, "max_length": 0, "display_name": "File Path"}}, "display_name": "Outputs"}', 1, '2025-02-08 14:40:52', '2025-02-08 14:40:48', '2025-02-08 14:40:53', 1);
INSERT INTO `custom_tools` (`id`, `team_id`, `user_id`, `app_id`, `config`, `input_variables`, `dependencies`, `code`, `output_type`, `output_variables`, `publish_status`, `published_time`, `created_time`, `updated_time`, `status`) VALUES (324, 1, 32, 2652, NULL, '{"name": "output", "type": "object", "properties": {"content": {"name": "content", "type": "string", "value": "", "required": true, "max_length": 0, "display_name": "File Content"}, "file_suffix": {"name": "file_suffix", "type": "string", "value": "", "required": true, "max_length": 0, "display_name": "File Suffix"}}, "display_name": "", "to_string_keys": ""}', '{"python3": []}', '{"python3":"import os\\nimport uuid\\n\\ndef main(content: str, file_suffix: str) -> dict:\\n    try:\\n        # Generate a random UUID for the file name\\n        unique_id = uuid.uuid4()\\n\\n        # Split the file_suffix by \'.\' and take the last part as the actual suffix\\n        suffix_parts = file_suffix.split(\'.\')\\n        if len(suffix_parts) > 1:\\n            actual_suffix = suffix_parts[-1]\\n        else:\\n            actual_suffix = file_suffix\\n\\n        # Ensure the suffix starts with a dot\\n        if not actual_suffix.startswith(\'.\'):\\n            actual_suffix = f\\".{actual_suffix}\\"\\n\\n        # Construct the file name with the correct suffix\\n        file_name = f\\"{unique_id}{actual_suffix}\\"\\n\\n        # Create the storage directory if it doesn\'t exist\\n        storage_dir = \'/storage\'\\n        os.makedirs(storage_dir, exist_ok=True)\\n\\n        # Create the full storage path\\n        storage_path = os.path.join(storage_dir, file_name)\\n\\n        # Write the content to the file\\n        with open(storage_path, \'w\') as file:\\n            file.write(content)\\n        status = \'True\'\\n    except Exception as e:\\n        # Capture any exception and set the status to the exception message\\n        status = str(e)\\n\\n    # Return the status and the file path\\n    return {\'status\': status, \'file_path\': f\\"file://{storage_path}\\"}"}', 4, '{"name": "output", "type": "object", "properties": {"status": {"name": "status", "type": "string", "value": "", "required": false, "max_length": 0, "display_name": "Execution Status"}, "file_path": {"name": "file_path", "type": "string", "value": "", "required": false, "max_length": 0, "display_name": "File Path"}}, "display_name": "", "to_string_keys": ""}', 0, NULL, '2025-02-08 14:40:48', '2025-02-08 19:09:37', 1);
