INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES ('20', '1', 'o1', '1', '1', '200000', '100000', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES ('21', '1', 'o1-mini', '1', '1', '128000', '65536', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES ('22', '1', 'o1-preview', '1', '1', '128000', '32768', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `sort_order`, `created_time`, `updated_time`, `status`) VALUES ('20', '1', '20', '{\"n\": 1, \"stop\": null, \"model\": \"o1\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}', '0', '93', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `sort_order`, `created_time`, `updated_time`, `status`) VALUES ('21', '1', '21', '{\"n\": 1, \"stop\": null, \"model\": \"o1-mini\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}', '0', '94', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `sort_order`, `created_time`, `updated_time`, `status`) VALUES ('22', '1', '22', '{\"n\": 1, \"stop\": null, \"model\": \"o1-preview\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}', '0', '95', CURRENT_TIMESTAMP, NULL, '1');

UPDATE `model_configurations` SET `sort_order` = '92' WHERE `model_configurations`.`id` = 9;

UPDATE `model_configurations` SET `config` = '{\"n\": 1, \"stop\": null, \"model\": \"gpt-4o\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}' WHERE `model_configurations`.`id` = 3;
UPDATE `model_configurations` SET `config` = '{\"n\": 1, \"stop\": null, \"model\": \"gpt-4o-mini\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}' WHERE `model_configurations`.`id` = 5;
UPDATE `model_configurations` SET `config` = '{\"n\": 1, \"stop\": null, \"model\": \"gpt-4-turbo\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}' WHERE `model_configurations`.`id` = 6;
UPDATE `model_configurations` SET `config` = '{\"n\": 1, \"stop\": null, \"model\": \"gpt-4-1106-preview\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}' WHERE `model_configurations`.`id` = 7;
UPDATE `model_configurations` SET `config` = '{\"n\": 1, \"stop\": null, \"model\": \"gpt-3.5-turbo\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}' WHERE `model_configurations`.`id` = 8;
UPDATE `model_configurations` SET `config` = '{\"model\": \"doubao-1-5-pro-256k-250115\", \"temperature\": 1, \"model_kwargs\": {}, \"organization\": null, \"openai_proxy\": null, \"timeout\": null, \"max_retries\": 2, \"streaming\": false, \"n\": 1, \"max_tokens\": null, \"tiktoken_model_name\": null, \"default_headers\": null, \"default_query\": null, \"http_client\": null, \"http_async_client\": null, \"stop_sequences\": null}' WHERE `model_configurations`.`id` = 15;
UPDATE `model_configurations` SET `config` = '{\"model\": \"doubao-1-5-pro-32k-250115\", \"temperature\": 1, \"model_kwargs\": {}, \"organization\": null, \"openai_proxy\": null, \"timeout\": null, \"max_retries\": 2, \"streaming\": false, \"n\": 1, \"max_tokens\": null, \"tiktoken_model_name\": null, \"default_headers\": null, \"default_query\": null, \"http_client\": null, \"http_async_client\": null, \"stop_sequences\": null}' WHERE `model_configurations`.`id` = 16;
UPDATE `model_configurations` SET `config` = '{\"model\": \"doubao-1-5-lite-32k-250115\", \"temperature\": 1, \"model_kwargs\": {}, \"organization\": null, \"openai_proxy\": null, \"timeout\": null, \"max_retries\": 2, \"streaming\": false, \"n\": 1, \"max_tokens\": null, \"tiktoken_model_name\": null, \"default_headers\": null, \"default_query\": null, \"http_client\": null, \"http_async_client\": null, \"stop_sequences\": null}' WHERE `model_configurations`.`id` = 17;
UPDATE `model_configurations` SET `config` = '{\"model\": \"doubao-pro-256k-241115\", \"temperature\": 1, \"model_kwargs\": {}, \"organization\": null, \"openai_proxy\": null, \"timeout\": null, \"max_retries\": 2, \"streaming\": false, \"n\": 1, \"max_tokens\": null, \"tiktoken_model_name\": null, \"default_headers\": null, \"default_query\": null, \"http_client\": null, \"http_async_client\": null, \"stop_sequences\": null}' WHERE `model_configurations`.`id` = 18;
UPDATE `model_configurations` SET `config` = '{\"model\": \"doubao-lite-128k-240828\", \"temperature\": 1, \"model_kwargs\": {}, \"organization\": null, \"openai_proxy\": null, \"timeout\": null, \"max_retries\": 2, \"streaming\": false, \"n\": 1, \"max_tokens\": null, \"tiktoken_model_name\": null, \"default_headers\": null, \"default_query\": null, \"http_client\": null, \"http_async_client\": null, \"stop_sequences\": null}' WHERE `model_configurations`.`id` = 19;