INSERT INTO `suppliers` (`id`, `name`, `mode`, `created_time`, `updated_time`, `status`) VALUES (NULL, 'Anthropic', '1', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `supplier_configurations` (`id`, `team_id`, `supplier_id`, `config`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '3', '{}', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (NULL, '3', 'claude-3-5-sonnet-latest', '1', '1', '200000', '8192', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (NULL, '3', 'claude-3-5-haiku-latest', '1', '1', '200000', '8192', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (NULL, '3', 'claude-3-opus-latest', '1', '1', '200000', '4096', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (NULL, '3', 'claude-3-sonnet-20240229', '1', '1', '200000', '4096', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (NULL, '3', 'claude-3-haiku-20240307', '1', '1', '200000', '4096', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '9', '{\"model_name\": \"claude-3-5-sonnet-latest\",\"max_tokens_to_sample\": 8192,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '10', '{\"model_name\": \"claude-3-5-haiku-latest\",\"max_tokens_to_sample\": 8192,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '11', '{\"model_name\": \"claude-3-opus-latest\",\"max_tokens_to_sample\": 4096,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '12', '{\"model_name\": \"claude-3-sonnet-20240229\",\"max_tokens_to_sample\": 4096,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '13', '{\"model_name\": \"claude-3-haiku-20240307\",\"max_tokens_to_sample\": 4096,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');