INSERT INTO `suppliers` (`id`, `name`, `mode`, `created_time`, `updated_time`, `status`) VALUES (3, 'Anthropic', '1', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `supplier_configurations` (`id`, `team_id`, `supplier_id`, `config`, `created_time`, `updated_time`, `status`) VALUES (NULL, '1', '3', '{}', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (9, '1', 'o3-mini', '1', '1', '200000', '100000', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (10, '3', 'claude-3-5-sonnet-latest', '1', '1', '200000', '8192', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (11, '3', 'claude-3-5-haiku-latest', '1', '1', '200000', '8192', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (12, '3', 'claude-3-opus-latest', '1', '1', '200000', '4096', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (13, '3', 'claude-3-sonnet-20240229', '1', '1', '200000', '4096', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `models` (`id`, `supplier_id`, `name`, `type`, `mode`, `max_context_tokens`, `max_output_tokens`, `created_time`, `updated_time`, `status`) VALUES (14, '3', 'claude-3-haiku-20240307', '1', '1', '200000', '4096', CURRENT_TIMESTAMP, NULL, '1');

INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (9, '1', '9', '{\"n\": 1, \"stop\": null, \"model\": \"o3-mini\", \"streaming\": false, \"max_tokens\": null, \"http_client\": null, \"max_retries\": 2, \"temperature\": 1, \"model_kwargs\": {}, \"openai_proxy\": null, \"default_query\": null, \"default_headers\": null, \"openai_api_base\": null, \"request_timeout\": null, \"http_async_client\": null, \"openai_organization\": null, \"tiktoken_model_name\": null}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (10, '1', '10', '{\"model_name\": \"claude-3-5-sonnet-latest\",\"max_tokens_to_sample\": 8192,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (11, '1', '11', '{\"model_name\": \"claude-3-5-haiku-latest\",\"max_tokens_to_sample\": 8192,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (12, '1', '12', '{\"model_name\": \"claude-3-opus-latest\",\"max_tokens_to_sample\": 4096,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (13, '1', '13', '{\"model_name\": \"claude-3-sonnet-20240229\",\"max_tokens_to_sample\": 4096,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');
INSERT INTO `model_configurations` (`id`, `team_id`, `model_id`, `config`, `default_used`, `created_time`, `updated_time`, `status`) VALUES (14, '1', '14', '{\"model_name\": \"claude-3-haiku-20240307\",\"max_tokens_to_sample\": 4096,\"temperature\": null,\"top_k\": null,\"top_p\": null,\"timeout\": null,\"max_retries\": 2,\"anthropic_api_url\": null,\"default_headers\": null,\"model_kwargs\": {},\"streaming\": false}', '0', CURRENT_TIMESTAMP, NULL, '1');