credentials_for_provider:
  endpoint:
    help:
      en_US: Get your OpenSearch endpoint from your provider
      pt_BR: Get your OpenSearch endpoint from your provider
      zh_Hans: 从您的OpenSearch服务商那里获取您的endpoint
    label:
      en_US: Endpoint
      pt_BR: Endpoint
      zh_Hans: 服务地址
    placeholder:
      en_US: host:port,...
      pt_BR: host:port,...
      zh_Hans: host:port,...
    required: true
    type: text-input
    url: https://opensearch-project.github.io/opensearch-py/api-ref/clients/opensearch_client.html
  password:
    help:
      en_US: Get your password
      pt_BR: Get your password
      zh_Hans: 您在OpenSearch服务商那里设置的密码
    label:
      en_US: password
      pt_BR: password
      zh_Hans: 密码
    placeholder:
      en_US: Please input your password
      pt_BR: Please input your password
      zh_Hans: 请输入你的密码
    required: false
    type: secret-input
    url: https://opensearch-project.github.io/opensearch-py/api-ref/clients/opensearch_client.html
  user:
    help:
      en_US: Get your user name
      pt_BR: Get your user name
      zh_Hans: 您在OpenSearch服务商那里设置的账号名称
    label:
      en_US: User
      pt_BR: User
      zh_Hans: 用户名
    placeholder:
      en_US: Please input your user name
      pt_BR: Please input your user name
      zh_Hans: 请输入你的用户名
    required: true
    type: text-input
    url: https://opensearch-project.github.io/opensearch-py/api-ref/clients/opensearch_client.html
extra:
  python:
    source: provider/opensearch.py
identity:
  author: nexusai
  description:
    en_US: search information by OpenSearch
    pt_BR: search information by OpenSearch
    zh_Hans: search information by OpenSearch
  icon: icon.svg
  label:
    en_US: OpenSearch
    pt_BR: OpenSearch
    zh_Hans: OpenSearch
  name: opensearch
tools:
- tools/query.yaml
