credentials_for_provider:
  app_key:
    help:
      en_US: Obtain your App Key from DingTalk Developer Console
      zh_Hans: 从钉钉开发者控制台获取您的AppKey
    label:
      en_US: App Key
      zh_Hans: AppKey
    placeholder:
      en_US: Please input your App Key
      zh_Hans: 请输入您的AppKey
    required: true
    type: text-input
    url: https://open.dingtalk.com/document/orgapp/obtain-the-access_token-of-an-internal-app
  app_secret:
    help:
      en_US: Obtain your App Secret from DingTalk Developer Console
      zh_Hans: 从钉钉开发者控制台获取您的应用密钥
    label:
      en_US: App Secret
      zh_Hans: AppSecret
    placeholder:
      en_US: Please input your App Secret
      zh_Hans: 请输入您的AppSecret
    required: true
    type: secret-input
    url: https://open.dingtalk.com/document/orgapp/obtain-the-access_token-of-an-internal-app
extra:
  python:
    source: provider/dingtalk_yida.py
identity:
  author: nexusai
  description:
    en_US: Tool for creating and submitting DingTalk form instances.
    zh_Hans: 用于创建和提交钉钉表单实例的工具。
  icon: icon.svg
  label:
    en_US: DingTalk Yida
    zh_Hans: 钉钉宜搭
  name: dingtalk_yida
  tags:
  - social
  - productivity
tools:
- tools/batch_delete_form_instances.yaml
- tools/batch_get_form_instances.yaml
- tools/batch_save_form_instances.yaml
- tools/batch_update_form_instances.yaml
- tools/delete_form_instance.yaml
- tools/get_form_fields.yaml
- tools/get_form_instance.yaml
- tools/get_forms.yaml
- tools/save_form_instance.yaml
- tools/search_form_instances.yaml
- tools/update_form_instance.yaml
