credentials_for_provider:
  access_token:
    help:
      en_US: Get your access token from Dropbox App Console
      ja_JP: Dropbox アプリコンソールからアクセストークンを取得してください
      pt_BR: Obtenha seu token de acesso no Console de Aplicativos do Dropbox
      zh_Hans: 从 Dropbox 应用控制台获取您的访问令牌
      zh_Hant: 請從 Dropbox 應用程式主控台取得您的存取權杖
    label:
      en_US: Access Token
      ja_JP: アクセストークン
      pt_BR: Token de Acesso
      zh_Hans: 访问令牌
      zh_Hant: 存取權杖
    placeholder:
      en_US: Please input your Dropbox access token
      ja_JP: Dropbox アクセストークンを入力してください
      pt_BR: Por favor, insira seu token de acesso do Dropbox
      zh_Hans: 请输入您的 Dropbox 访问令牌
      zh_Hant: 請輸入您的 Dropbox 存取權杖
    required: true
    type: secret-input
    url: https://www.dropbox.com/developers/apps
extra:
  python:
    source: provider/dropbox.py
identity:
  author: nexusai
  description:
    en_US: Interact with Dropbox files and folders
    ja_JP: Dropbox のファイルとフォルダを操作します
    pt_BR: Interaja com arquivos e pastas do Dropbox
    zh_Hans: 与 Dropbox 文件和文件夹交互
    zh_Hant: 與 Dropbox 檔案和資料夾互動
  icon: icon.svg
  label:
    en_US: Dropbox
    ja_JP: Dropbox
    pt_BR: Dropbox
    zh_Hans: Dropbox
    zh_Hant: Dropbox
  name: dropbox
tools:
- tools/list_files.yaml
- tools/search_files.yaml
- tools/upload_file.yaml
- tools/download_file.yaml
- tools/create_folder.yaml
- tools/delete_file.yaml
