extra:
  python:
    source: provider/minio.py
identity:
  author: nexusai
  description:
    en_US: Tools for writing content to minio and reading from minio
    pt_BR: Tools for writing content to minio and reading from minio
    zh_Hans: Tools for writing content to minio and reading from minio
  icon: minio.svg
  label:
    en_US: minio
    pt_BR: minio
    zh_Hans: minio
  name: minio
tools:
- tools/minio_reader.yaml
- tools/minio_writer.yaml
